### ISSUE TITLE
Source Organization should link to organization search

### ISSUE THREAD

**Issue by eby** [steiza/docstore#10]
Just putting in a couple things to meet @vielmetti 's hope for parity with old version.

In a2docs.org when viewing a doc the source organization goes to a search for other things for that organization.

**Comment by eby** [comment]
Related to this it might be good to have some searches be fielded. If you go to the org screen it gives right number but clicking on the org gives a generic search. Ex: https://a2docs.aadl.org/search?query=Ann+Arbor+District+Library

**Comment by steiza** [comment]
With https://github.com/steiza/docstore/commit/21fc5bc07dafa30d0e3398de26006bfef6a2980c you should now be able to specify what field you want to search (by default it searches all fields) and I linkified the source organization and submitter in many places to a search with the field specified.
