### ISSUE TITLE
Document details page: "date posted" metadata

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#11]
Cf https://a2docs.aadl.org/view/292

A date field displayed to the reader should include not only "date requested" and "date received" but also "date posted". This ensures that there's at least one date displayed.

The relevant bit from the old system here:

![screen shot 2016-02-29 at 5 59 17 am](https://cloud.githubusercontent.com/assets/35047/13392604/aaacfbec-dea9-11e5-95d9-ac2dfce43912.png)

**Comment by steiza** [comment]
Oops! Here's a fix: https://github.com/steiza/docstore/commit/e34d7518381fd8bbdf3938f536ae07f6c01dd3ef
