### ISSUE TITLE
500: Internal Server Error on upload

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#14]
I just tried to upload the CARD presentation on the 1,4 Dioxane plume and got an internal server error. The time was approximately 0815 on 2/29.

500: Internal Server Error

![screen shot 2016-02-29 at 8 16 17 am](https://cloud.githubusercontent.com/assets/35047/13395453/cbf285ca-debc-11e5-8845-f9ac0a0ffbbf.png)

**Comment by eby** [comment]
This should be fixed now. When I rolled out the fixed storage dump for multiple files I forgot to update the permissions.

**Comment by eby** [comment]
I'm not sure how easy it would be but probably should have it check the storage directory permissions and warn you if it won't be able to write.

**Comment by steiza** [comment]
Sounds good to me! Check out https://github.com/steiza/docstore/commit/ba44b459479becf20f1acd8e429de4b8ae84ea4b.
