### ISSUE TITLE
Several templates' title blocks have "A2" hardcoded in them 

### ISSUE THREAD

**Issue by cdzombak** [steiza/docstore#17]
Looking at `index.html`, `org.html`, `search.html` and probably others, the title typically includes "A2":

```
{% block title %}
Search A2 Government Document Repository
{% end %}
```

I note that `base.html` uses `{{region}}`. I'm too tired to fix this now and verify it actually works on my machine (and I am not familiar with Tornado's templating so I'll need to test this locally), so filing this as a note for later.

**Comment by steiza** [comment]
Nice catch - should be fixed by https://github.com/steiza/docstore/commit/67700abb2a7469c6dcd3f41a57c0af7a770b2d2f

**Comment by cdzombak** [comment]
:+1: thanks, @steiza!
