### ISSUE TITLE
Add Document form should allow multiple files per document

### ISSUE THREAD

**Issue by eby** [steiza/docstore#3]
Feature request to bring it up to the old a2docs format.

The old setup allowed this by cloning the browse field. Not sure if easier to do it as a multiselect browse instead.

![multiple-files](https://cloud.githubusercontent.com/assets/107030/13234461/b2ce17e8-d986-11e5-972f-631e3b0621a0.png)

**Comment by vielmetti** [comment]
Given a choice I'd do the multiselect browse; it's typical to have a set of docs all in a directory, and the current browse clone gets awkward if you want to do a bigger document dump.

**Comment by eby** [comment]
Related to this, was one of the original goals have a pdf viewer online? We'll need to think about how that looks when a bunch of pdfs in one dump. 

Did the original allow you to download all the docs in one go or was a list you downloaded individually?

**Comment by eby** [comment]
Nevermind, I see examples from your other issue.

**Comment by steiza** [comment]
Supporting multiple files was easier than I thought (https://github.com/steiza/docstore/commit/47c981d9a5e8181fdd24d13a3f197aa96ea8223a)! It has a new database schema and I had to re-run the legacy import - I'll send an email with details.
