### ISSUE TITLE
500 error when not logged in

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#32]
![Screen Shot 2021-09-21 at 11 35 38 PM](https://user-images.githubusercontent.com/35047/134279585-6f9a16d8-4b92-409a-ac1f-bf7120bfbfdf.png)

When I hit a2docs.org/review as an un-logged in user, I get this 500 error. I'm trying
to review a submission.

**Comment by vielmetti** [comment]
Fix in https://github.com/steiza/docstore/commit/11e74f14b0a82bb1e9dba9f87a0ea78471fb490e

**Comment by steiza** [comment]
I believe this has been deployed!
