### ISSUE TITLE
500: Internal Server Error after upload to a2docs

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#35]
On the evening of 2022-06-11 I set up an upload of 3 files to a2docs (FOIA 1258).
The upload failed with an Internal Server Error.

No idea what went wrong.

**Comment by steiza** [comment]
I also submitted a test upload, which resulted in a HTTP 500 / Internal Server Error. @eby could you take a look at the server logs?

I'm going to guess this has something to do with the email notifications. I logged in to https://a2docs.org/admin/ and went to https://a2docs.org/review and saw that my test upload succeeded and was waiting for review, but I didn't get the review email notification. It looks like there's a couple of uploads from December 2021 until now, so the email notifications might have been broken for awhile.

**Comment by eby** [comment]
You are right. Our email provider did a security update sometime ago that flagged every account that sent automated email as compromised and reset it. I fixed all the server level smtp but missed that this was also in the docstore settings file. I've fixed that and restarted it so hopefully it is good now.
