### ISSUE TITLE
Narrative / Description field should have more detailed prompts for info and be larger

### ISSUE THREAD

**Issue by eby** [steiza/docstore#4]
Feature request from @vielmetti

Original a2docs.org has the text

> Add any relevant details about the documents. What are the documents about? Were there any problems or revelations? If your request was denied, what reason was given? What is the larger issue?

Could use this text as the alt or discuss a different form of the text.

The styling of the box should probably be more fluid for browser size.

**Comment by eby** [comment]
Actually looking at @vielmetti 's sample upload, maybe this field should support markdown so some basic formatting can be done. Looks like quite a few python parsers available but don't know the ease of render in current setup.

**Comment by vielmetti** [comment]
I'd love to have markdown of some flavor in the comment field, that could be very useful.

**Comment by steiza** [comment]
https://github.com/steiza/docstore/commit/b55994b60a195ca74292d29a6e87e14f762febac is a quick fix for the placeholder text and to make the text input area larger.

Markdown is an interesting idea, but we should probably do something about multi-file upload (https://github.com/steiza/docstore/issues/3) first.

**Comment by eby** [comment]
I rolled out the latest master which fixes the narrative and size. Already separate issue for the markdown display so closing this issue.
