### ISSUE TITLE
Source Organization field should be an autocomplete to prevent duplicates and aid search

### ISSUE THREAD

**Issue by eby** [steiza/docstore#5]
Feature request from @vielmetti

Old system had an autocomplete on the source organization field. It also had a couple common ones.

It my test of the old autocomplete it was still showing quite a few slight spelling differences so obviously isn't fool proof but would aid in some of the browsing if most things are uniform.

**Comment by steiza** [comment]
This should be fixed by https://github.com/steiza/docstore/commit/a477831306b2a08c6f7ce722e85f7cdfafab1e1c. It adds auto-complete to the add doc interface and also the edit doc interface (to help with cleanup / de-duplication).

Still working on the other requests. : )
