### ISSUE TITLE
Feature: Narrative Description field to support Markdown formatting

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#7]
Noted in #4, this feature would support and render Markdown in the Narrative Description field.

Per that discussion, this is probably behind #3 (multiple file uploads).

**Comment by steiza** [comment]
This also ended up being a lot easier than I thought. It the python libraries markdown to generate the html and bleach to constrain the output. Take a look at https://github.com/steiza/docstore/commit/7480cedfb0cfebd33c14e69f4426bdb6d64a56ff or the attached screenshot.

![markdown](https://cloud.githubusercontent.com/assets/167759/13359228/0368424e-dc81-11e5-9f37-82576cf30cd1.png)
