### ISSUE TITLE
File import: confirm that import includes all files for multi-file imports

### ISSUE THREAD

**Issue by vielmetti** [steiza/docstore#9]
Related to #3 -

The current a2docs has a number of docs where a single document id is associated with multiple files, e.g.

http://a2docs.org/doc/292/ "Ann Arbor Fire Department response times"

which is different from 

https://a2docs.aadl.org/view/292 "Ann Arbor Golf Proposal for Huron Hills"

I'm not sure where the ID skew is coming from, but the goal is to preserve the old URLs so that Arborwiki doesn't require a bunch of updates.

**Comment by eby** [comment]
Looks like latest commits and updated DB/storage fixed this https://a2docs.aadl.org/view/292

**Comment by vielmetti** [comment]
Looks good!
